services:

  mysql:
    image: subalakx/digital-wallet-database:latest

    container_name: digital-wallet-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pRoot@12345"]
      interval: 10s
      timeout: 5s
      retries: 10


  backend:
    image: subalakx/digital-wallet-backend:latest

    container_name: digital-wallet-backend

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/digital_wallet?useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: Root@12345
      CORS_ALLOWED_ORIGINS: http://localhost

    depends_on:
      mysql:
        condition: service_healthy


  frontend:
    image: subalakx/digital-wallet-frontend:latest

    container_name: digital-wallet-frontend

    ports:
      - "80:80"

    depends_on:
      - backend


volumes:
  mysql_data: